// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: phone.proto

package com.sys.hbase;

public final class Phone {
  private Phone() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PhoneDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sys.hbase.PhoneDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 手机号码
     * </pre>
     *
     * <code>required string dnum = 1;</code>
     * @return Whether the dnum field is set.
     */
    boolean hasDnum();
    /**
     * <pre>
     * 手机号码
     * </pre>
     *
     * <code>required string dnum = 1;</code>
     * @return The dnum.
     */
    String getDnum();
    /**
     * <pre>
     * 手机号码
     * </pre>
     *
     * <code>required string dnum = 1;</code>
     * @return The bytes for dnum.
     */
    com.google.protobuf.ByteString
        getDnumBytes();

    /**
     * <pre>
     * 通话时长
     * </pre>
     *
     * <code>required string length = 2;</code>
     * @return Whether the length field is set.
     */
    boolean hasLength();
    /**
     * <pre>
     * 通话时长
     * </pre>
     *
     * <code>required string length = 2;</code>
     * @return The length.
     */
    String getLength();
    /**
     * <pre>
     * 通话时长
     * </pre>
     *
     * <code>required string length = 2;</code>
     * @return The bytes for length.
     */
    com.google.protobuf.ByteString
        getLengthBytes();

    /**
     * <pre>
     * 类型 0-接听；1-拨出 
     * </pre>
     *
     * <code>required string type = 3;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <pre>
     * 类型 0-接听；1-拨出 
     * </pre>
     *
     * <code>required string type = 3;</code>
     * @return The type.
     */
    String getType();
    /**
     * <pre>
     * 类型 0-接听；1-拨出 
     * </pre>
     *
     * <code>required string type = 3;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * 动作时间
     * </pre>
     *
     * <code>required string date = 4;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <pre>
     * 动作时间
     * </pre>
     *
     * <code>required string date = 4;</code>
     * @return The date.
     */
    String getDate();
    /**
     * <pre>
     * 动作时间
     * </pre>
     *
     * <code>required string date = 4;</code>
     * @return The bytes for date.
     */
    com.google.protobuf.ByteString
        getDateBytes();
  }
  /**
   * Protobuf type {@code com.sys.hbase.PhoneDetail}
   */
  public static final class PhoneDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sys.hbase.PhoneDetail)
      PhoneDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PhoneDetail.newBuilder() to construct.
    private PhoneDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneDetail() {
      dnum_ = "";
      length_ = "";
      type_ = "";
      date_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PhoneDetail();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              dnum_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              length_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              type_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              date_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Phone.internal_static_com_sys_hbase_PhoneDetail_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Phone.internal_static_com_sys_hbase_PhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PhoneDetail.class, Builder.class);
    }

    private int bitField0_;
    public static final int DNUM_FIELD_NUMBER = 1;
    private volatile Object dnum_;
    /**
     * <pre>
     * 手机号码
     * </pre>
     *
     * <code>required string dnum = 1;</code>
     * @return Whether the dnum field is set.
     */
    @Override
    public boolean hasDnum() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 手机号码
     * </pre>
     *
     * <code>required string dnum = 1;</code>
     * @return The dnum.
     */
    @Override
    public String getDnum() {
      Object ref = dnum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dnum_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 手机号码
     * </pre>
     *
     * <code>required string dnum = 1;</code>
     * @return The bytes for dnum.
     */
    @Override
    public com.google.protobuf.ByteString
        getDnumBytes() {
      Object ref = dnum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dnum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private volatile Object length_;
    /**
     * <pre>
     * 通话时长
     * </pre>
     *
     * <code>required string length = 2;</code>
     * @return Whether the length field is set.
     */
    @Override
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * 通话时长
     * </pre>
     *
     * <code>required string length = 2;</code>
     * @return The length.
     */
    @Override
    public String getLength() {
      Object ref = length_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          length_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 通话时长
     * </pre>
     *
     * <code>required string length = 2;</code>
     * @return The bytes for length.
     */
    @Override
    public com.google.protobuf.ByteString
        getLengthBytes() {
      Object ref = length_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        length_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile Object type_;
    /**
     * <pre>
     * 类型 0-接听；1-拨出 
     * </pre>
     *
     * <code>required string type = 3;</code>
     * @return Whether the type field is set.
     */
    @Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * 类型 0-接听；1-拨出 
     * </pre>
     *
     * <code>required string type = 3;</code>
     * @return The type.
     */
    @Override
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 类型 0-接听；1-拨出 
     * </pre>
     *
     * <code>required string type = 3;</code>
     * @return The bytes for type.
     */
    @Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 4;
    private volatile Object date_;
    /**
     * <pre>
     * 动作时间
     * </pre>
     *
     * <code>required string date = 4;</code>
     * @return Whether the date field is set.
     */
    @Override
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * 动作时间
     * </pre>
     *
     * <code>required string date = 4;</code>
     * @return The date.
     */
    @Override
    public String getDate() {
      Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          date_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 动作时间
     * </pre>
     *
     * <code>required string date = 4;</code>
     * @return The bytes for date.
     */
    @Override
    public com.google.protobuf.ByteString
        getDateBytes() {
      Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDnum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dnum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, length_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, date_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dnum_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, length_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, date_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PhoneDetail)) {
        return super.equals(obj);
      }
      PhoneDetail other = (PhoneDetail) obj;

      if (hasDnum() != other.hasDnum()) return false;
      if (hasDnum()) {
        if (!getDnum()
            .equals(other.getDnum())) return false;
      }
      if (hasLength() != other.hasLength()) return false;
      if (hasLength()) {
        if (!getLength()
            .equals(other.getLength())) return false;
      }
      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (!getType()
            .equals(other.getType())) return false;
      }
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDnum()) {
        hash = (37 * hash) + DNUM_FIELD_NUMBER;
        hash = (53 * hash) + getDnum().hashCode();
      }
      if (hasLength()) {
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getLength().hashCode();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PhoneDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PhoneDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sys.hbase.PhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sys.hbase.PhoneDetail)
        PhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Phone.internal_static_com_sys_hbase_PhoneDetail_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Phone.internal_static_com_sys_hbase_PhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PhoneDetail.class, Builder.class);
      }

      // Construct using com.sys.hbase.Phone.PhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dnum_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Phone.internal_static_com_sys_hbase_PhoneDetail_descriptor;
      }

      @Override
      public PhoneDetail getDefaultInstanceForType() {
        return PhoneDetail.getDefaultInstance();
      }

      @Override
      public PhoneDetail build() {
        PhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PhoneDetail buildPartial() {
        PhoneDetail result = new PhoneDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dnum_ = dnum_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PhoneDetail) {
          return mergeFrom((PhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PhoneDetail other) {
        if (other == PhoneDetail.getDefaultInstance()) return this;
        if (other.hasDnum()) {
          bitField0_ |= 0x00000001;
          dnum_ = other.dnum_;
          onChanged();
        }
        if (other.hasLength()) {
          bitField0_ |= 0x00000002;
          length_ = other.length_;
          onChanged();
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000004;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasDate()) {
          bitField0_ |= 0x00000008;
          date_ = other.date_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        if (!hasDnum()) {
          return false;
        }
        if (!hasLength()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!hasDate()) {
          return false;
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PhoneDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object dnum_ = "";
      /**
       * <pre>
       * 手机号码
       * </pre>
       *
       * <code>required string dnum = 1;</code>
       * @return Whether the dnum field is set.
       */
      public boolean hasDnum() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 手机号码
       * </pre>
       *
       * <code>required string dnum = 1;</code>
       * @return The dnum.
       */
      public String getDnum() {
        Object ref = dnum_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dnum_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 手机号码
       * </pre>
       *
       * <code>required string dnum = 1;</code>
       * @return The bytes for dnum.
       */
      public com.google.protobuf.ByteString
          getDnumBytes() {
        Object ref = dnum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dnum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 手机号码
       * </pre>
       *
       * <code>required string dnum = 1;</code>
       * @param value The dnum to set.
       * @return This builder for chaining.
       */
      public Builder setDnum(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 手机号码
       * </pre>
       *
       * <code>required string dnum = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDnum() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dnum_ = getDefaultInstance().getDnum();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 手机号码
       * </pre>
       *
       * <code>required string dnum = 1;</code>
       * @param value The bytes for dnum to set.
       * @return This builder for chaining.
       */
      public Builder setDnumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dnum_ = value;
        onChanged();
        return this;
      }

      private Object length_ = "";
      /**
       * <pre>
       * 通话时长
       * </pre>
       *
       * <code>required string length = 2;</code>
       * @return Whether the length field is set.
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * 通话时长
       * </pre>
       *
       * <code>required string length = 2;</code>
       * @return The length.
       */
      public String getLength() {
        Object ref = length_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            length_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 通话时长
       * </pre>
       *
       * <code>required string length = 2;</code>
       * @return The bytes for length.
       */
      public com.google.protobuf.ByteString
          getLengthBytes() {
        Object ref = length_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          length_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 通话时长
       * </pre>
       *
       * <code>required string length = 2;</code>
       * @param value The length to set.
       * @return This builder for chaining.
       */
      public Builder setLength(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 通话时长
       * </pre>
       *
       * <code>required string length = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = getDefaultInstance().getLength();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 通话时长
       * </pre>
       *
       * <code>required string length = 2;</code>
       * @param value The bytes for length to set.
       * @return This builder for chaining.
       */
      public Builder setLengthBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <pre>
       * 类型 0-接听；1-拨出 
       * </pre>
       *
       * <code>required string type = 3;</code>
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * 类型 0-接听；1-拨出 
       * </pre>
       *
       * <code>required string type = 3;</code>
       * @return The type.
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 类型 0-接听；1-拨出 
       * </pre>
       *
       * <code>required string type = 3;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 类型 0-接听；1-拨出 
       * </pre>
       *
       * <code>required string type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 类型 0-接听；1-拨出 
       * </pre>
       *
       * <code>required string type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 类型 0-接听；1-拨出 
       * </pre>
       *
       * <code>required string type = 3;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }

      private Object date_ = "";
      /**
       * <pre>
       * 动作时间
       * </pre>
       *
       * <code>required string date = 4;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * 动作时间
       * </pre>
       *
       * <code>required string date = 4;</code>
       * @return The date.
       */
      public String getDate() {
        Object ref = date_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            date_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 动作时间
       * </pre>
       *
       * <code>required string date = 4;</code>
       * @return The bytes for date.
       */
      public com.google.protobuf.ByteString
          getDateBytes() {
        Object ref = date_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          date_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 动作时间
       * </pre>
       *
       * <code>required string date = 4;</code>
       * @param value The date to set.
       * @return This builder for chaining.
       */
      public Builder setDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 动作时间
       * </pre>
       *
       * <code>required string date = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 动作时间
       * </pre>
       *
       * <code>required string date = 4;</code>
       * @param value The bytes for date to set.
       * @return This builder for chaining.
       */
      public Builder setDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        date_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sys.hbase.PhoneDetail)
    }

    // @@protoc_insertion_point(class_scope:com.sys.hbase.PhoneDetail)
    private static final PhoneDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PhoneDetail();
    }

    public static PhoneDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<PhoneDetail>
        PARSER = new com.google.protobuf.AbstractParser<PhoneDetail>() {
      @Override
      public PhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneDetail> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PhoneDetail> getParserForType() {
      return PARSER;
    }

    @Override
    public PhoneDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface dayPhoneDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.sys.hbase.dayPhoneDetail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    java.util.List<PhoneDetail>
        getDayPhoneDetailList();
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    PhoneDetail getDayPhoneDetail(int index);
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    int getDayPhoneDetailCount();
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    java.util.List<? extends PhoneDetailOrBuilder>
        getDayPhoneDetailOrBuilderList();
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    PhoneDetailOrBuilder getDayPhoneDetailOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.sys.hbase.dayPhoneDetail}
   */
  public static final class dayPhoneDetail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.sys.hbase.dayPhoneDetail)
      dayPhoneDetailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use dayPhoneDetail.newBuilder() to construct.
    private dayPhoneDetail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private dayPhoneDetail() {
      dayPhoneDetail_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new dayPhoneDetail();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private dayPhoneDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                dayPhoneDetail_ = new java.util.ArrayList<PhoneDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              dayPhoneDetail_.add(
                  input.readMessage(PhoneDetail.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          dayPhoneDetail_ = java.util.Collections.unmodifiableList(dayPhoneDetail_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Phone.internal_static_com_sys_hbase_dayPhoneDetail_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Phone.internal_static_com_sys_hbase_dayPhoneDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dayPhoneDetail.class, Builder.class);
    }

    public static final int DAYPHONEDETAIL_FIELD_NUMBER = 1;
    private java.util.List<PhoneDetail> dayPhoneDetail_;
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    @Override
    public java.util.List<PhoneDetail> getDayPhoneDetailList() {
      return dayPhoneDetail_;
    }
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    @Override
    public java.util.List<? extends PhoneDetailOrBuilder>
        getDayPhoneDetailOrBuilderList() {
      return dayPhoneDetail_;
    }
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    @Override
    public int getDayPhoneDetailCount() {
      return dayPhoneDetail_.size();
    }
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    @Override
    public PhoneDetail getDayPhoneDetail(int index) {
      return dayPhoneDetail_.get(index);
    }
    /**
     * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
     */
    @Override
    public PhoneDetailOrBuilder getDayPhoneDetailOrBuilder(
        int index) {
      return dayPhoneDetail_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDayPhoneDetailCount(); i++) {
        if (!getDayPhoneDetail(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dayPhoneDetail_.size(); i++) {
        output.writeMessage(1, dayPhoneDetail_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dayPhoneDetail_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dayPhoneDetail_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dayPhoneDetail)) {
        return super.equals(obj);
      }
      dayPhoneDetail other = (dayPhoneDetail) obj;

      if (!getDayPhoneDetailList()
          .equals(other.getDayPhoneDetailList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDayPhoneDetailCount() > 0) {
        hash = (37 * hash) + DAYPHONEDETAIL_FIELD_NUMBER;
        hash = (53 * hash) + getDayPhoneDetailList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dayPhoneDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dayPhoneDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dayPhoneDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dayPhoneDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dayPhoneDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dayPhoneDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dayPhoneDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dayPhoneDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dayPhoneDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dayPhoneDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dayPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dayPhoneDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dayPhoneDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.sys.hbase.dayPhoneDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.sys.hbase.dayPhoneDetail)
        dayPhoneDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Phone.internal_static_com_sys_hbase_dayPhoneDetail_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Phone.internal_static_com_sys_hbase_dayPhoneDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dayPhoneDetail.class, Builder.class);
      }

      // Construct using com.sys.hbase.Phone.dayPhoneDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDayPhoneDetailFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (dayPhoneDetailBuilder_ == null) {
          dayPhoneDetail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dayPhoneDetailBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Phone.internal_static_com_sys_hbase_dayPhoneDetail_descriptor;
      }

      @Override
      public dayPhoneDetail getDefaultInstanceForType() {
        return dayPhoneDetail.getDefaultInstance();
      }

      @Override
      public dayPhoneDetail build() {
        dayPhoneDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public dayPhoneDetail buildPartial() {
        dayPhoneDetail result = new dayPhoneDetail(this);
        int from_bitField0_ = bitField0_;
        if (dayPhoneDetailBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            dayPhoneDetail_ = java.util.Collections.unmodifiableList(dayPhoneDetail_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dayPhoneDetail_ = dayPhoneDetail_;
        } else {
          result.dayPhoneDetail_ = dayPhoneDetailBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dayPhoneDetail) {
          return mergeFrom((dayPhoneDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dayPhoneDetail other) {
        if (other == dayPhoneDetail.getDefaultInstance()) return this;
        if (dayPhoneDetailBuilder_ == null) {
          if (!other.dayPhoneDetail_.isEmpty()) {
            if (dayPhoneDetail_.isEmpty()) {
              dayPhoneDetail_ = other.dayPhoneDetail_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDayPhoneDetailIsMutable();
              dayPhoneDetail_.addAll(other.dayPhoneDetail_);
            }
            onChanged();
          }
        } else {
          if (!other.dayPhoneDetail_.isEmpty()) {
            if (dayPhoneDetailBuilder_.isEmpty()) {
              dayPhoneDetailBuilder_.dispose();
              dayPhoneDetailBuilder_ = null;
              dayPhoneDetail_ = other.dayPhoneDetail_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dayPhoneDetailBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDayPhoneDetailFieldBuilder() : null;
            } else {
              dayPhoneDetailBuilder_.addAllMessages(other.dayPhoneDetail_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        for (int i = 0; i < getDayPhoneDetailCount(); i++) {
          if (!getDayPhoneDetail(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dayPhoneDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dayPhoneDetail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PhoneDetail> dayPhoneDetail_ =
        java.util.Collections.emptyList();
      private void ensureDayPhoneDetailIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dayPhoneDetail_ = new java.util.ArrayList<PhoneDetail>(dayPhoneDetail_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          PhoneDetail, PhoneDetail.Builder, PhoneDetailOrBuilder> dayPhoneDetailBuilder_;

      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public java.util.List<PhoneDetail> getDayPhoneDetailList() {
        if (dayPhoneDetailBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dayPhoneDetail_);
        } else {
          return dayPhoneDetailBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public int getDayPhoneDetailCount() {
        if (dayPhoneDetailBuilder_ == null) {
          return dayPhoneDetail_.size();
        } else {
          return dayPhoneDetailBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public PhoneDetail getDayPhoneDetail(int index) {
        if (dayPhoneDetailBuilder_ == null) {
          return dayPhoneDetail_.get(index);
        } else {
          return dayPhoneDetailBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder setDayPhoneDetail(
          int index, PhoneDetail value) {
        if (dayPhoneDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.set(index, value);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder setDayPhoneDetail(
          int index, PhoneDetail.Builder builderForValue) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.set(index, builderForValue.build());
          onChanged();
        } else {
          dayPhoneDetailBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(PhoneDetail value) {
        if (dayPhoneDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(value);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(
          int index, PhoneDetail value) {
        if (dayPhoneDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(index, value);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(
          PhoneDetail.Builder builderForValue) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(builderForValue.build());
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addDayPhoneDetail(
          int index, PhoneDetail.Builder builderForValue) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.add(index, builderForValue.build());
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder addAllDayPhoneDetail(
          Iterable<? extends PhoneDetail> values) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dayPhoneDetail_);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder clearDayPhoneDetail() {
        if (dayPhoneDetailBuilder_ == null) {
          dayPhoneDetail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public Builder removeDayPhoneDetail(int index) {
        if (dayPhoneDetailBuilder_ == null) {
          ensureDayPhoneDetailIsMutable();
          dayPhoneDetail_.remove(index);
          onChanged();
        } else {
          dayPhoneDetailBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public PhoneDetail.Builder getDayPhoneDetailBuilder(
          int index) {
        return getDayPhoneDetailFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public PhoneDetailOrBuilder getDayPhoneDetailOrBuilder(
          int index) {
        if (dayPhoneDetailBuilder_ == null) {
          return dayPhoneDetail_.get(index);  } else {
          return dayPhoneDetailBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public java.util.List<? extends PhoneDetailOrBuilder>
           getDayPhoneDetailOrBuilderList() {
        if (dayPhoneDetailBuilder_ != null) {
          return dayPhoneDetailBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dayPhoneDetail_);
        }
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public PhoneDetail.Builder addDayPhoneDetailBuilder() {
        return getDayPhoneDetailFieldBuilder().addBuilder(
            PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public PhoneDetail.Builder addDayPhoneDetailBuilder(
          int index) {
        return getDayPhoneDetailFieldBuilder().addBuilder(
            index, PhoneDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .com.sys.hbase.PhoneDetail dayPhoneDetail = 1;</code>
       */
      public java.util.List<PhoneDetail.Builder>
           getDayPhoneDetailBuilderList() {
        return getDayPhoneDetailFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          PhoneDetail, PhoneDetail.Builder, PhoneDetailOrBuilder>
          getDayPhoneDetailFieldBuilder() {
        if (dayPhoneDetailBuilder_ == null) {
          dayPhoneDetailBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              PhoneDetail, PhoneDetail.Builder, PhoneDetailOrBuilder>(
                  dayPhoneDetail_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          dayPhoneDetail_ = null;
        }
        return dayPhoneDetailBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.sys.hbase.dayPhoneDetail)
    }

    // @@protoc_insertion_point(class_scope:com.sys.hbase.dayPhoneDetail)
    private static final dayPhoneDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dayPhoneDetail();
    }

    public static dayPhoneDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<dayPhoneDetail>
        PARSER = new com.google.protobuf.AbstractParser<dayPhoneDetail>() {
      @Override
      public dayPhoneDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new dayPhoneDetail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<dayPhoneDetail> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<dayPhoneDetail> getParserForType() {
      return PARSER;
    }

    @Override
    public dayPhoneDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sys_hbase_PhoneDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sys_hbase_PhoneDetail_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_sys_hbase_dayPhoneDetail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_sys_hbase_dayPhoneDetail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013phone.proto\022\rcom.sys.hbase\"G\n\013PhoneDet" +
      "ail\022\014\n\004dnum\030\001 \002(\t\022\016\n\006length\030\002 \002(\t\022\014\n\004typ" +
      "e\030\003 \002(\t\022\014\n\004date\030\004 \002(\t\"D\n\016dayPhoneDetail\022" +
      "2\n\016dayPhoneDetail\030\001 \003(\0132\032.com.sys.hbase." +
      "PhoneDetail"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_sys_hbase_PhoneDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_sys_hbase_PhoneDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sys_hbase_PhoneDetail_descriptor,
        new String[] { "Dnum", "Length", "Type", "Date", });
    internal_static_com_sys_hbase_dayPhoneDetail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_sys_hbase_dayPhoneDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_sys_hbase_dayPhoneDetail_descriptor,
        new String[] { "DayPhoneDetail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
